<a href="https://colab.research.google.com/github/Aashman28/demo/blob/main/Copy_of_CV_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>
<h1><strong> Computer Vision assignment 2 </strong></h1>
</center>

**This assignment will challenge your understanding of basic python programming paradigm and evaluate your intution of numpy **

- Make sure all the implementations are general and should work for any test case that we use
- Numpy link: https://www.youtube.com/watch?v=QUT1VHiLmmI&t=958s
- the above link will provide a general introduction to numpy - if additional information is needed refer to the documentation



## **Instructions :**


- Make a copy of this Colab notebook (else any changes you make wont be saved)
- Feel free to add more code blocks in between questions if you feel you need it


---
## **Numpy**

In [ ]:
import numpy as np
import string


#### `Q1) create a 1-D numpy array with elements from 0 to 10`

In [ ]:
a = np.linspace(0,10,11)
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]



#### `Q2) Create a 2D numpy array of shape = (7,8)`

In [ ]:
a = np.zeros((7,8))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


#### `Q3) Create a 1-D numpy array of size 10 with random integer values ranging from 40 to 69. Once created print the sorted array.`

In [ ]:
array_1d = np.random.randint(40, 69, 10)
sorted_array = np.sort(array_1d)
print(sorted_array)




[40 40 43 47 49 52 52 54 56 60]


#### `Q4) Find indices of non-zero elements in [1,5,0,0,53,78,4,0,21,79,0,4,5,17]`

In [ ]:
array = np.array([1,5,0,0,53,78,4,0,21,79,0,4,5,17])
non_zero_indices= np.nonzero(array)
print(non_zero_indices)

(array([ 0,  1,  4,  5,  6,  8,  9, 11, 12, 13]),)



#### `Q5) Create a random vector and replce the maximum element by 10`

In [ ]:
random_vector = np.random.rand(5)
print(random_vector)
highest_value=random_vector.max()
# used max() instead of argmax() to cover the cases in which multiple occurences of highest value are there
max_indices = np.where(random_vector==highest_value)[0]
random_vector[max_indices]=10
print(random_vector)


**Q6) Create a 2d array with 1 on the border and 0 inside**


In [ ]:
my_array = np.zeros([10,10],int)
my_array[0, :] = 1
my_array[-1, :]=1
my_array[:,0]=1
my_array[:,-1]=1
print(my_array)

 Q7) Create a 8x8 matrix and fill it with a checkerboard pattern


In [ ]:
checkerboard = np.zeros((8, 8), dtype=int)

for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 1:
            checkerboard[i, j] = 1

print(checkerboard)

Q8) Get all the dates corresponding to the month of October 2023.(Dont just print them directly)

In [ ]:
import datetime
start_date = datetime.date(2023, 10, 1)
end_date = datetime.date(2023, 10, 31)
delta = end_date - start_date
dates_in_october = np.arange(start_date, end_date + datetime.timedelta(days=1), dtype='datetime64[D]')
print(dates_in_october)


Q9) Randomly place p elements in a 2D array. (take p=3 and 10x10 array)

In [ ]:
my_array = np.zeros([10,10],int)
for i in range(0,3):
    row = np.random.randint(1,10)
    column = np.random.randint(1,10)
    my_array[row,column]=1
print(my_array)

Q10)Generate a random matrix. Subtract the mean of each row of a matrix from it.

In [ ]:
random_matrix = np.random.rand(4,5)
solution_matrix = random_matrix - random_matrix.mean(axis=1,keepdims=True)
#(keepdims = true) keeps the dimensions of matrix same and ensures proper subtraction/broadcasting
print(solution_matrix)


Q11) Consider the vector [1, 2, 3, 4, 5], build a new vector with 3 consecutive zeros interleaved between each value?

In [ ]:
vector = np.array([1, 2, 3, 4, 5], int)
new_vector_length = len(vector)+(len(vector)-1)*3
new_vector = np.zeros(new_vector_length)
new_vector[::4] = vector[::1]
print(new_vector)